[project]

name = "geoip"
version = "0.0.1"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "Bindings for the GeoIP library"
license = "ISC"

[lib]

name = "geoip"
path = "src/geoip/lib.rs"
