[project]
name = "geoip"
version = "0.0.8"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "Bindings for the GeoIP library"
license = "ISC"
homepage = "https://github.com/jedisct1/rust-geoip"
repository = "https://github.com/jedisct1/rust-geoip"

[lib]
name = "geoip"
path = "src/geoip/lib.rs"

[dependencies.geoip-sys]
geoip-sys = "*"

[dependencies.rustc-serialize]
rustc-serialize = "*"
